version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres-dev:
    image: postgres:15-alpine
    container_name: unitel-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: unitel_employees_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - unitel-dev-network

  # Development Next.js Application
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: unitel-app-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://dev_user:dev_password@postgres-dev:5432/unitel_employees_dev
      - JWT_SECRET=dev-jwt-secret-key
      - NEXT_PUBLIC_APP_URL=http://localhost:3001
    ports:
      - "3001:3000"
    depends_on:
      - postgres-dev
    networks:
      - unitel-dev-network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_dev_data:
    driver: local

networks:
  unitel-dev-network:
    driver: bridge
